-- Per-user cross-portfolio research digest generated by generate-watchlist-digest Edge Function.
-- One row per user (upserted on regeneration). Sources include papers, filings, reports.

create table public.watchlist_digest (
  user_id         uuid        primary key references auth.users(id) on delete cascade,
  digest_text     text        not null default '',
  sources         jsonb       not null default '[]',
  -- snapshot of watchlist slugs at generation time (detect staleness when list changes)
  slugs_snapshot  text[]      not null default '{}',
  generated_at    timestamptz not null default now(),
  model           text,
  -- true while Edge Function is running; prevents concurrent regeneration
  is_generating   boolean     not null default false
);

comment on table public.watchlist_digest is
  'Cross-portfolio synthesis digest per user, generated from watchlist company research contexts.';
comment on column public.watchlist_digest.sources is
  'Array of {title, url, type, relevance} — papers, filings, news, reports.';
comment on column public.watchlist_digest.slugs_snapshot is
  'Watchlist slug list at generation time; used to detect when watchlist changed.';

alter table public.watchlist_digest enable row level security;

create policy "users own their digest"
  on public.watchlist_digest
  for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Index for fast single-user lookup (primary key covers this, but explicit for clarity)
create index if not exists watchlist_digest_user_id_idx
  on public.watchlist_digest (user_id);
