-- Add synthesis column to company_research_cache.
-- Stores a 3-4 sentence narrative paragraph generated by the research
-- function (Perplexity sonar-pro) alongside the raw source items.

alter table public.company_research_cache
  add column if not exists synthesis text;
